name: Java CI
on: [push, pull_request]

jobs:
  buildOnJava17:
    name: build on java17
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
          cache: 'maven'
          cache-dependency-path: 'pom.xml'
      - name: Build with Maven
        run: mvn package -P !develop
